# Example of an unmigrated package.

package(default_visibility = [
    "//tests:__subpackages__",
])

licenses(["unencumbered"])

cc_library(
    name = "library_with_legacy_license_clause",
    srcs = ["file_under_notice.cc"],
)

cc_library(
    name = "another_library_with_legacy_license_clause",
    srcs = ["file_under_notice.cc"],
)
