# License declaration and compliance checking rules.

py_binary(
    name = "checker_demo",
    srcs = ["checker_demo.py"],
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

exports_files(["diff_test.sh"])
