# This workflow generates and build tests the workspace.
name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # tag=v3.5.2
      - name: Analyze
        run: bazel build --nobuild //...
      - name: Build
        run: bazel build //...
      - name: Test
        run: bazel test //...
